version: '3'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "${PGSQL_PORT:-5432}:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 30
  web:
    build: .
    command: ./bin/rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails
    ports:
      - "${WEB_PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data: